# permissions for end users to edit autoworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoworkload-editor-role
rules:
- apiGroups:
  - workload.tomo-kon.com
  resources:
  - autoworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.tomo-kon.com
  resources:
  - autoworkloads/status
  verbs:
  - get
