# permissions for end users to view autoworkloads.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoworkload-viewer-role
rules:
- apiGroups:
  - github.com
  resources:
  - autoworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.com
  resources:
  - autoworkloads/status
  verbs:
  - get
